name: Manual Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build release from (e.g., v0.0.2)'
        required: true
        type: string
      create_release:
        description: 'Create GitHub release'
        required: true
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  build:
    name: Build Kiwi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output: kiwi-linux-amd64
          - goos: darwin
            goarch: amd64
            output: kiwi-macos-amd64
          - goos: windows
            goarch: amd64
            output: kiwi-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -ldflags="-s -w" -o ${{ matrix.output }} ./cmd/kiwi
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
          
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.create_release == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Create release directory
        run: mkdir -p release
        
      - name: Copy artifacts to release directory
        run: |
          find . -type f -name "kiwi-*" -exec cp {} release/ \;
          cd release
          sha256sum * > checksums.txt
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: release/*
          generate_release_notes: true
